version: '3.8'
services:
    db:
        image: postgres:15
        container_name: tp_app_db
        env_file:
            - .env-non-dev
        ports:
            - 5432:5432

    tp:
        image: tp_app_image
        container_name: tp_app
        build:
            context: .
        env_file:
            - .env-non-dev
        depends_on:
            - db
        command: ['/tp_app_fastapi/docker/app.sh']
        ports:
            - 7777:8000
