"""пользователю добавил флаг access_bot

Revision ID: 2bc1c2ed24f7
Revises: 6b5efb1ab198
Create Date: 2024-03-24 12:23:02.444632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bc1c2ed24f7'
down_revision: Union[str, None] = '6b5efb1ab198'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_tg', sa.Column('access_bot', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_tg', 'access_bot')
    # ### end Alembic commands ###
